### ISSUE TITLE
Leading bit is incorrect

### ISSUE THREAD

**Issue by drewtato** [hertg/epochalypse#1]
Note: you've been posted to Hacker News: https://news.ycombinator.com/item?id=34284759

You've overwritten the first bit to be `1` when this is not how signed 32-bit integers are represented. The overflow should happen at `0111 1111 1111 1111 1111 1111 1111 1111`.

https://github.com/hertg/epochalypse/blob/5fba7970966c5d5f46b17d0a85b240b813c37a18/index.html#L109

If this were me, I'd remove the first digit and not replace it with anything.

```js
byte1.innerText = bits.substr(1, 7);
```

**Comment by hertg** [comment]
Good catch, thanks!
It was late at night when I wrote that :smile:
